
# main menu
[[main]]
name = "Home"
URL = "/"
weight = 1

[[main]]
name = "Research"
URL = "research"
weight = 2
hasChildren = true

# publications page
[[main]]
name = "Publications"
URL = "publications"
weight = 3

[[main]]
name = "People"
weight = 4
hasChildren = true

	[[main]]
	parent = "People"
	name = "About Dave"
	URL = "about"
	weight = 1

	[[main]]
	parent = "People"
	name = "Lab Members"
	URL = "people"
	weight = 2

[[main]]
name = "Products"
weight = 5
hasChildren = true

	[[main]]
	parent = "Products"
	weight = 1
	name = "Data & Software"
	URL = "data_software/"

	[[main]]
	parent = "Products"
	name = "Multimedia"
	URL = "project/"
	weight = 2

[[main]]
name = "Blog"
URL = "blog"
weight = 6

[[main]]
name = "Join Us!"
URL = "join"
weight = 7

# [[main]]
# name = "Projects"
# URL = "project"
# weight = 5
# hasChildren = true
# 
#   [[main]]
#   parent = "Projects"
#   name = "Land Cover"
#   URL = "lcluc"

# footer menu
[[footer]]
name = "About"
URL = "about"
weight = 1
[[footer]]
name = "Research"
URL = "research"
weight = 2
[[footer]]
name = "Lab Members"
URL = "people"
weight = 3
[[footer]]
name = "Multimedia"
URL = "project"
weight = 3
[[footer]]
